apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- simple-reader.yaml
#  - ../../base
namespace: sreader
images:
- name: sreader-dev-db
  newName: ghcr.io/natsume-197/simple-epub-reader
  newTag: v0.0.5-alpha
