---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: sreader-pv
  labels:
    type: local
    app: sreader
spec:
  storageClassName: manual
  capacity:
    storage: 200Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/nvme1/sreaderdb/"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sreader-pvc
  labels:
    app: sreader
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 200Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sreader-deployment
  labels:
    app: sreader
spec:
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: sreader
  template:
    metadata:
      labels:
        app: sreader
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
        - image: sreader-dev-db
          name: sreader-dev-db
          volumeMounts:
            - name: sreader-volume
              mountPath: /app/data
      volumes:
        - name: sreader-volume
          persistentVolumeClaim:
            claimName: sreader-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: sreader-service
  labels:
    app: sreader
spec:
  selector:
    app: sreader
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sreader-ingress
  labels:
    app: sreader
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/proxy-body-size: "10G"
    nginx.org/client-max-body-size: "10G"
    cert-manager.io/cluster-issuer: clusterissuer-prod
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - sreader.nadeshiko.co
      secretName: certificate-sreader
  rules:
    - host: sreader.nadeshiko.co
      http:
        paths:
          - pathType: Prefix
            path: /
            backend:
              service:
                name: sreader-service
                port:
                  number: 8080
